spring:
  application:
    name: portal_instituto_caapora
  datasource:
    url: jdbc:postgresql://localhost:5432/dbInstituto_Caapora
    username: ${DATABASE_USERNAME:postgres} #Variavel de Ambiente
    password: ${DATABASE_PASSWORD:postgres} #Variavel de Ambiente
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect